# -*- coding: utf-8 -*-
"""
Editorial data for ROUTING.md
==============================
This is the ONE place for judgment calls `tools/generate_routing.py` cannot
derive by measuring the DB/repo: task-intent routing advice, why an
environment quirk exists, which anchors are worth sanity-checking and why.

It is still single-source and reviewable (checked in, diffable, imported by
exactly one script), and it CANNOT silently disagree with the measured
sections: the generator renders every fact below verbatim next to the live
measurement it relates to, and `scripts/validate_ssot_consistency.py`'s
`check_routing_regeneration` fails the build the moment the committed
ROUTING.md stops matching what this file + the live repo actually produce.

REVIEWED_DATE below is a human/agent judgment timestamp, NOT the generation
timestamp (the generator embeds no wall-clock time anywhere -- ROUTING.md
must render byte-identical on every run against an unchanged repo, or the
regeneration-diff gate could never pass). Bump REVIEWED_DATE when you
actually re-examine and re-approve the editorial content below; do not bump
it automatically.
"""

REVIEWED_DATE = "2026-07-25"

# What superseded the previous hand-written ROUTING.md, and why this one is
# structured the way it is. Rendered near the top of the file.
STATUS_NOTE = (
    "Supersedes the 2026-07-25 hand-written ROUTING.md. That version is the "
    "artifact this task (P3) was commissioned to fix: it was accurate at the "
    "time but had no regeneration mechanism, so nothing forced it to stay "
    "accurate. It also framed the I2 axis-agnostic storage refactor "
    "(`analysis_derivation` table, `pipeline/query_engine/axis_registry.py`) "
    "as future work ('superseded once I2 lands') when I2 had, by the time "
    "of generation, already landed -- exactly the kind of drift a "
    "hand-maintained routing doc cannot catch on its own. This file is "
    "regenerated by `tools/generate_routing.py`; a regeneration-diff gate "
    "in `scripts/validate_ssot_consistency.py` fails CI if it drifts from "
    "the committed file. To change routing content: edit the generator "
    "(for MEASURED sections) or this file (for EDITORIAL sections), then "
    "run `python3 tools/generate_routing.py --write` and commit the result. "
    "Never hand-edit ROUTING.md directly -- the next regeneration will "
    "silently discard hand edits, and the diff gate will catch (and reject) "
    "exactly that discrepancy in the meantime."
)

# Section 3 in the rendered doc: "Your task -> where the context lives".
# Columns: task, authority (files/functions to read), verify (test to run),
# never_touch (the one thing that would make this task unsafe).
TASK_INTENT_ROUTING = [
    {
        "task": "Query items / axes",
        "authority": "`pipeline/query_engine/selective_fetcher.py` "
                     "(`get_question`, `get_questions_batch`)",
        "verify": "`tests/test_selective_fetcher.py`",
        "never_touch": "\u2014",
    },
    {
        "task": "Understand the taxonomy",
        "authority": "`docs/Taxonomy_Spec.md` (DDL SSoT), `docs/SSOT_MAP.md`, "
                     "`pipeline/query_engine/axis_registry.py` (axis identity, "
                     "status, kind -- see \u00a72 below). The 8-axis taxonomy "
                     "itself is under owner review; do not extend it before "
                     "that review concludes.",
        "verify": "`scripts/validate_ssot_consistency.py`",
        "never_touch": "editing DDL without updating Spec; treating "
                       "`axis_analysis` flat columns as the storage model "
                       "(it is now a read-only compatibility VIEW over "
                       "`analysis_derivation` -- see \u00a72)",
    },
    {
        "task": "Parse / re-extract PDFs",
        "authority": "`pipeline/dataset_parser/hwp_layout_reconstructor.py`, "
                     "`pipeline/dataset_parser/hwp_pua_map.json` (verified, do "
                     "not edit), `pipeline/dataset_parser/pdf_segmenter.py`",
        "verify": "`tests/test_hwp_layout_reconstructor.py`",
        "never_touch": "`storage/parsed_dataset.db` directly",
    },
    {
        "task": "Answer keys",
        "authority": "`pipeline/dataset_parser/answer_binder.py`, "
                     "`raw_dataset/*-answer.png`",
        "verify": "cross-track: items 1\u201322 must agree across DIF/GEO/PRO "
                  "for the same session",
        "never_touch": "\u2014",
    },
    {
        "task": "Change review state",
        "authority": "`pipeline/query_engine/review_state.py` **only**",
        "verify": "`tests/test_review_state_machine.py`",
        "never_touch": "direct `UPDATE review_status` -- forbidden by "
                       "`docs/SSOT_MAP.md` \u00a76, and blocked at the DB "
                       "layer by the append-only triggers checked in "
                       "`check_ddl`",
    },
    {
        "task": "Provenance of a claim",
        "authority": "`pipeline/query_engine/claim_provenance.py`, "
                     "`claim_provenance` table",
        "verify": "`tests/test_claim_provenance.py`",
        "never_touch": "synthesising provenance in a reader",
    },
    {
        "task": "Add a data-quality gate",
        "authority": "`scripts/validate_ssot_consistency.py`",
        "verify": "must FAIL on a known-broken fixture, PASS on a healthy one",
        "never_touch": "weakening any existing `check_*` function -- add a "
                       "new one instead",
    },
    {
        "task": "Add or reason about a new axis",
        "authority": "`pipeline/query_engine/axis_registry.py` (register "
                     "identity/status/kind -- optional, storage is "
                     "open-world), `pipeline/migrate_db_axis_agnostic.py` "
                     "(storage model)",
        "verify": "`tests/test_axis_registry.py`, "
                  "`tests/test_migrate_axis_agnostic.py`",
        "never_touch": "adding a new hardcoded `axis_analysis` DDL column "
                       "-- that is precisely the I2 refactor undid",
    },
    {
        "task": "Agent prompts / axis specs",
        "authority": "`pipeline/agents_spec/*.md`",
        "verify": "\u2014",
        "never_touch": "\u2014",
    },
    {
        "task": "Project status",
        "authority": "`PROJECT_STATE.json` (SSoT). `MANIFEST.json` "
                     "references it, never duplicates it.",
        "verify": "`scripts/validate_ssot_consistency.py`",
        "never_touch": "duplicating dynamic state into MANIFEST.json",
    },
]

# Section 4: environment notes NOT safely re-measurable on every generator
# run (re-checking them would mean deliberately triggering the failure mode
# they describe -- e.g. actually corrupting the mounted DB -- which this
# task is explicitly forbidden from doing). Kept editorial and dated;
# package/CLI *availability* facts are measured live instead (see \u00a74 in
# the rendered doc) and are not duplicated here.
ENVIRONMENT_CONSTRAINTS_EDITORIAL = [
    "SQLite writes directly on the mounted repo FAIL with `disk I/O error`, "
    "and leave a stale `storage/parsed_dataset.db-journal` that then blocks "
    "*reads*. Correct procedure: (1) `cp storage/parsed_dataset.db /tmp/w.db` "
    "(2) mutate `/tmp/w.db` (3) `cat /tmp/w.db > storage/parsed_dataset.db` "
    "(4) `: > storage/parsed_dataset.db-journal` to truncate any stale "
    "journal. Not re-verified on every generation run: doing so would mean "
    "deliberately reproducing a mount corruption on every invocation of "
    "this generator, which is unacceptable even as a test.",
    "`rm` is not permitted on the mount. To discard a file, move it into a "
    "`_to_delete/` folder and say so.",
    "Each bash call is capped at 45 s and shares no cwd/env with the next. "
    "Batch long corpus runs and use absolute paths. Not re-verified each "
    "run: proving the cap requires deliberately exceeding it.",
    "The test suite has side effects: it writes `storage/backups/` and "
    "touches `storage/html_reports/202606_MATH_DIF_15_report.html`. Ignore "
    "or revert; do not \"fix\".",
]

# Section 6: known-good anchors. The (item_id, expected_answer,
# expected_correct_value, expected_latex_substring) tuples are spot-verified
# live against the DB by the generator every run (see MEASURED markers in
# the rendered doc) -- only the *prose* explaining why these two items are
# useful regression anchors is editorial.
KNOWN_GOOD_ANCHORS = [
    {
        "item_id": "202606_MATH_DIF_15",
        "expected_answer": 4,
        "expected_correct_value": 27,
        "expected_latex_substring": "\\int_{p}^{p+3}\u2223f(x)\u2223dx\u2260\u2223\\int_{p}^{p+3}f(x)dx\u2223",
        "why": "The one item with real (non-placeholder) analysis on all "
               "8 axes -- the only place in the corpus where axis output can "
               "be checked against ground truth rather than just against "
               "'is it a stub'.",
    },
    {
        "item_id": "202109_MATH_DIF_07",
        "expected_answer": 4,
        "expected_correct_value": -3,
        "expected_latex_substring": "\\sum_{k=1}^{n}\\frac{a_{k+1}-a_{k}}{a_{k}a_{k+1}}=\\frac{1}{n}",
        "why": "Subscripts inside construct bodies (`a_{k+1}`, `a_{k}` "
               "nested under a `\\sum`/`\\frac`) are the historic HWP-parsing "
               "failure mode; check this item first after touching the "
               "layout reconstructor.",
    },
]

# Section 7: "open, unfixed" items that are genuinely editorial judgment
# (severity framing, historical cost estimates) rather than a live count.
# Anything that IS a live count (axis real-ratios, correct_rate emptiness,
# axis kind/category per axis_registry.py) is rendered from measurement
# instead and is NOT duplicated here.
OPEN_UNFIXED_EDITORIAL = [
    "The 8-axis taxonomy itself is under owner review -- do not build on it "
    "or extend it before that review concludes (see axis_registry.py "
    "`status` field per axis, rendered in \u00a72, for which axes are "
    "`under_review` vs `active`).",
    "`axis_analysis`/`analysis_derivation` historically hardcoded 8 axis "
    "columns in the DDL and roughly 91 scattered code sites before the I2 "
    "axis-agnostic refactor (`pipeline/query_engine/axis_registry.py`, "
    "`pipeline/migrate_db_axis_agnostic.py`) decoupled axis identity from "
    "schema. The ~91 figure is a one-time historical estimate from that "
    "refactor, not something this generator re-derives each run.",
]
